# action.yml
name: 'Instana Release'
description: 'Create a release marker in Instana with the given name'
branding:
  icon: bookmark
  color: blue
inputs:
  releaseName:
    description: 'Name of the release'
    required: true
  releaseScope: >
    {
      "services": [
        {
          "name": "cart",
          "scopedTo": {
            "applications": [{ "name": "Nick-robotshop" }]
          }
        },
        { "name": "spring-boot" }
      ]
    }
outputs:
  timide:
    description: 'Release id'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.releaseName }}
    - ${{ inputs.releaseScope }}
